# .bashrc

# centos PS1
# [\u@\h \W]\$
export PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w\[\033[00m\]$(__git_ps1) \[\033[01;34m\]\t \r\n\$\[\033[00m\] '


# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [ -f /etc/bash_completion.d/yum.bash ]; then
	. /etc/bash_completion.d/yum.bash
fi

if [ -f /etc/bash_completion.d/git ]; then
	. /etc/bash_completion.d/git
fi

# User specific aliases and functions
alias vimr='vim -R'
