set termencoding=utf-8
set encoding=utf-8
set fileencoding=utf-8

"set fileencodings=utf-8,iso-2022-jp,euc-jp,ucs2le,ucs-2,cp932
"set fileencodings=utf-8,euc-jp,cp932

set nocompatible " vi

" enable backspace
" set backspace=indent,eol,start

set shiftwidth=4
set softtabstop=4
set tabstop=4

"show file name
set laststatus=2

" set row number
set number

" set hlsearch
" set wrapscan
" set showmatch

set ignorecase

" enable foldings
set foldmethod=marker

" syntax color
" syntax on
"colorscheme slate
"highlight LineNr ctermfg=darkgray

set backup
set backupdir=$HOME/.vim-backup
"set browsedir=buffer
set directory=$HOME/.vim-backup "スワップファイルディレクトリを指定する
"set history=1000


set list
set listchars=tab:>-,trail:_

